/********************************************************************************************************************************************/
/*                                                                                                                                          */
/*  Header-Datei: KM_App_Main.h                                                                                                             */
/*                                                                                                                                          */
/*  Prof. Dr. Lothar Zunker      02.06.2021                                                                                                 */
/*                                                                                                                                          */
/********************************************************************************************************************************************/
#pragma once

/************************************************************* System-Includes **************************************************************/
#include "PLC_SteuerungInterfaces.h"
#include "AdsR0.h"
#include "TcMath.h"

/*********************************************************** Anwender-Includes **************************************************************/
//######################################### Labor für Mechatronik ##########################################
#include "KM_GlobalObjects.h"
#include "KM_Level_A.h"
//##########################################################################################################

// parameter ids for TwinCAT module KM_App_Main with disabled code generation
// could be moved to PLC_SteuerungServices.h
const PTCID PID_KM_App_MainAdsPort        = 0x00000002;

class CKM_App_Main : public ITComObject, public ITcADI, public ITcWatchSource
///<AutoGeneratedContent id="InheritanceList">
	, public ITcCyclic
///</AutoGeneratedContent>
  , public CAdsR0FifoPort
  {
  public:
  DECLARE_IUNKNOWN               ()
  DECLARE_IPERSIST               (CID_PLC_SteuerungCKM_App_Main)
  DECLARE_ITCOMOBJECT_LOCKOP     ()
  DECLARE_ITCADI                 ()
  DECLARE_ITCWATCHSOURCE         ()
  DECLARE_OBJPARAWATCH_MAP       ()
  DECLARE_OBJDATAAREA_MAP        ()

                             CKM_App_Main           ();
  virtual                   ~CKM_App_Main           ();

  //HRESULT                 SetObjStatePS           (PTComInitDataHdr pInitData);
  //HRESULT                 SetObjStateSO           ();
  //HRESULT                 SetObjStateOS           ();
  //HRESULT                 SetObjStateSP           ();

  HRESULT                   AddModuleToCaller       ();
  VOID                      RemoveModuleFromCaller  ();


///<AutoGeneratedContent id="InterfaceMembers">
	// ITcCyclic
	virtual HRESULT TCOMAPI CycleUpdate(ITcTask* ipTask, ITcUnknown* ipCaller, ULONG_PTR context);

///</AutoGeneratedContent>

  virtual void              AdsReadWriteInd         (AmsAddr& rAddr, ULONG invokeId, ULONG indexGroup, ULONG indexOffset, ULONG cbReadLength, ULONG cbWriteLength, PVOID pWriteData);

  void                      SubmitAdsReadReq        ();
  virtual void              AdsReadCon              (AmsAddr& rAddr, ULONG invokeId, ULONG result, ULONG cbReadLength, PVOID pReadData);

  void                      SubmitAdsWriteReq       ();
  virtual void              AdsWriteCon             (AmsAddr& rAddr, ULONG invokeId, ULONG result, ULONG cbWriteLength);
 protected:
  DECLARE_ITCOMOBJECT_SETSTATE();

  // Tracing
  CTcTrace                         m_Trace;

///<AutoGeneratedContent id="Members">
	TcTraceLevel m_TraceLevelMax;
	WORD m_DefaultAdsPort;
	WORD m_ContextAdsPort;
	ULONG m_Counter;
	KM_App_MainInputs m_Inputs;
	KM_App_MainOutputs m_Outputs;
	ITcCyclicCallerInfoPtr m_spCyclicCaller;
///</AutoGeneratedContent>
  
  enum
    {
    invokeIdReadByOidAndPid = 1
    };
  ULONG                            m_ReadByOidAndPid;
  
  public:
  //######################################### Labor für Mechatronik ##########################################
  Zunker::C_KM_GlobalObjects*      KM_GlobalObjects;
  Zunker::C_KM_Level_A*            KM_Level_A;
  //##########################################################################################################
  }; //class CKM_App_Main 
