///////////////////////////////////////////////////////////////////////////////
// PLC_SteuerungInterfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "PLC_SteuerungServices.h"

///<AutoGeneratedContent id="Interfaces">
///</AutoGeneratedContent>
