///////////////////////////////////////////////////////////////////////////////
// PLC_SteuerungServices.h   07.04.2021

#pragma once

#include "TcServices.h"

const ULONG DrvID_PLC_Steuerung = 0x3F000000;
#define SRVNAME_PLC_STEUERUNG "PLC_Steuerung"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_PLC_SteuerungCKM_App_Main = {0x87d6b531,0x2a42,0x4271,{0x84,0xc2,0xe2,0x5b,0x37,0x1f,0x69,0x09}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_KM_App_MainDefaultAdsPort = 0x00000001;
const PTCID PID_KM_App_MainCounter = 0x00000003;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
#if !defined(_TC_TYPE_76B6B3E9_E99F_44B6_8408_F74DF0177542_INCLUDED_)
#define _TC_TYPE_76B6B3E9_E99F_44B6_8408_F74DF0177542_INCLUDED_
typedef struct _S_EK1100_Input_Prozessabbild
{
	USHORT State;
} S_EK1100_Input_Prozessabbild, *PS_EK1100_Input_Prozessabbild;
#endif // !defined(_TC_TYPE_76B6B3E9_E99F_44B6_8408_F74DF0177542_INCLUDED_)

#if !defined(_TC_TYPE_C82684E1_4AAA_4483_84B4_81E041C79E69_INCLUDED_)
#define _TC_TYPE_C82684E1_4AAA_4483_84B4_81E041C79E69_INCLUDED_
typedef struct _S_EK1100_Output_Prozessabbild
{
	SHORT Dummy;
} S_EK1100_Output_Prozessabbild, *PS_EK1100_Output_Prozessabbild;
#endif // !defined(_TC_TYPE_C82684E1_4AAA_4483_84B4_81E041C79E69_INCLUDED_)

#if !defined(_TC_TYPE_D05F841F_3A12_462E_9996_2F94A235C751_INCLUDED_)
#define _TC_TYPE_D05F841F_3A12_462E_9996_2F94A235C751_INCLUDED_
typedef struct _S_EL1012_Input_Prozessabbild
{
	bool Channel0_Input;
	bool Channel1_Input;
	bool WcState;
	bool InputToggle;
	USHORT State;
} S_EL1012_Input_Prozessabbild, *PS_EL1012_Input_Prozessabbild;
#endif // !defined(_TC_TYPE_D05F841F_3A12_462E_9996_2F94A235C751_INCLUDED_)

#if !defined(_TC_TYPE_BABEC5F7_76D6_4C43_8A8F_BB49AEDB9A88_INCLUDED_)
#define _TC_TYPE_BABEC5F7_76D6_4C43_8A8F_BB49AEDB9A88_INCLUDED_
typedef struct _S_EL1012_Output_Prozessabbild
{
	SHORT Dummy;
} S_EL1012_Output_Prozessabbild, *PS_EL1012_Output_Prozessabbild;
#endif // !defined(_TC_TYPE_BABEC5F7_76D6_4C43_8A8F_BB49AEDB9A88_INCLUDED_)

#if !defined(_TC_TYPE_4E95BB47_38FB_4D58_9CF6_E930171ED87E_INCLUDED_)
#define _TC_TYPE_4E95BB47_38FB_4D58_9CF6_E930171ED87E_INCLUDED_
typedef struct _S_EL1014_Input_Prozessabbild
{
	bool Channel0_Input;
	bool Channel1_Input;
	bool Channel2_Input;
	bool Channel3_Input;
	bool WcState;
	bool InputToggle;
	USHORT State;
} S_EL1014_Input_Prozessabbild, *PS_EL1014_Input_Prozessabbild;
#endif // !defined(_TC_TYPE_4E95BB47_38FB_4D58_9CF6_E930171ED87E_INCLUDED_)

#if !defined(_TC_TYPE_96DCE787_2941_445E_BA69_93A167F0ADC1_INCLUDED_)
#define _TC_TYPE_96DCE787_2941_445E_BA69_93A167F0ADC1_INCLUDED_
typedef struct _S_EL1014_Output_Prozessabbild
{
	SHORT Dummy;
} S_EL1014_Output_Prozessabbild, *PS_EL1014_Output_Prozessabbild;
#endif // !defined(_TC_TYPE_96DCE787_2941_445E_BA69_93A167F0ADC1_INCLUDED_)

#if !defined(_TC_TYPE_3669C52A_E118_411F_8855_F797F4EB70E5_INCLUDED_)
#define _TC_TYPE_3669C52A_E118_411F_8855_F797F4EB70E5_INCLUDED_
#pragma pack(push,1)
typedef struct _S_EL2004_Input_Prozessabbild
{
	bool WcState;
	USHORT State;
} S_EL2004_Input_Prozessabbild, *PS_EL2004_Input_Prozessabbild;
#pragma pack(pop)
#endif // !defined(_TC_TYPE_3669C52A_E118_411F_8855_F797F4EB70E5_INCLUDED_)

#if !defined(_TC_TYPE_11193B0B_67C3_4293_ACC6_0D5912C3A585_INCLUDED_)
#define _TC_TYPE_11193B0B_67C3_4293_ACC6_0D5912C3A585_INCLUDED_
typedef struct _S_EL2004_Output_Prozessabbild
{
	bool Channel0_Output;
	bool Channel1_Output;
	bool Channel2_Output;
	bool Channel3_Output;
} S_EL2004_Output_Prozessabbild, *PS_EL2004_Output_Prozessabbild;
#endif // !defined(_TC_TYPE_11193B0B_67C3_4293_ACC6_0D5912C3A585_INCLUDED_)

#if !defined(_TC_TYPE_48FF2450_8B03_4A45_AC7E_9A98C189414D_INCLUDED_)
#define _TC_TYPE_48FF2450_8B03_4A45_AC7E_9A98C189414D_INCLUDED_
#pragma pack(push,1)
typedef struct _S_EL2502_Input_Prozessabbild
{
	bool WcState;
	USHORT State;
	AmsAddr AdsAddr;
} S_EL2502_Input_Prozessabbild, *PS_EL2502_Input_Prozessabbild;
#pragma pack(pop)
#endif // !defined(_TC_TYPE_48FF2450_8B03_4A45_AC7E_9A98C189414D_INCLUDED_)

#if !defined(_TC_TYPE_8466D1D7_8491_401F_8664_5358D3B9C886_INCLUDED_)
#define _TC_TYPE_8466D1D7_8491_401F_8664_5358D3B9C886_INCLUDED_
typedef struct _S_EL2502_Output_Prozessabbild
{
	USHORT PWM_Output_0;
	USHORT PWM_Output_1;
} S_EL2502_Output_Prozessabbild, *PS_EL2502_Output_Prozessabbild;
#endif // !defined(_TC_TYPE_8466D1D7_8491_401F_8664_5358D3B9C886_INCLUDED_)

#if !defined(_TC_TYPE_9F7BD87D_3946_4125_9B35_9CE307487065_INCLUDED_)
#define _TC_TYPE_9F7BD87D_3946_4125_9B35_9CE307487065_INCLUDED_
typedef struct _S_EL3162_Input_Prozessabbild
{
	USHORT AI_Channel0_Status;
	SHORT AI_Channel0_Value;
	USHORT AI_Channel1_Status;
	SHORT AI_Channel1_Value;
	bool WcState;
	bool InputToggle;
	USHORT State;
	AmsAddr AdsAddr;
} S_EL3162_Input_Prozessabbild, *PS_EL3162_Input_Prozessabbild;
#endif // !defined(_TC_TYPE_9F7BD87D_3946_4125_9B35_9CE307487065_INCLUDED_)

#if !defined(_TC_TYPE_87186198_52D3_48D2_B1A3_863E9FA44FBF_INCLUDED_)
#define _TC_TYPE_87186198_52D3_48D2_B1A3_863E9FA44FBF_INCLUDED_
typedef struct _S_EL3162_Output_Prozessabbild
{
	SHORT Dummy;
} S_EL3162_Output_Prozessabbild, *PS_EL3162_Output_Prozessabbild;
#endif // !defined(_TC_TYPE_87186198_52D3_48D2_B1A3_863E9FA44FBF_INCLUDED_)

#if !defined(_TC_TYPE_BB60BB13_0328_483A_B179_7D92CE69F784_INCLUDED_)
#define _TC_TYPE_BB60BB13_0328_483A_B179_7D92CE69F784_INCLUDED_
typedef struct _S_EL3202_Input_Prozessabbild
{
	USHORT RTD_Status_0;
	SHORT RTD_Value_0;
	USHORT RTD_Status_1;
	SHORT RTD_Value_1;
	bool WcState;
	bool InputToggle;
	USHORT State;
	AmsAddr AdsAddr;
} S_EL3202_Input_Prozessabbild, *PS_EL3202_Input_Prozessabbild;
#endif // !defined(_TC_TYPE_BB60BB13_0328_483A_B179_7D92CE69F784_INCLUDED_)

#if !defined(_TC_TYPE_B2975D1D_4E49_48CC_9BB8_232E79FB3ED0_INCLUDED_)
#define _TC_TYPE_B2975D1D_4E49_48CC_9BB8_232E79FB3ED0_INCLUDED_
typedef struct _S_EL3202_Output_Prozessabbild
{
	SHORT Dummy;
} S_EL3202_Output_Prozessabbild, *PS_EL3202_Output_Prozessabbild;
#endif // !defined(_TC_TYPE_B2975D1D_4E49_48CC_9BB8_232E79FB3ED0_INCLUDED_)

#if !defined(_TC_TYPE_74959CEA_91AC_4705_A895_00BB30773892_INCLUDED_)
#define _TC_TYPE_74959CEA_91AC_4705_A895_00BB30773892_INCLUDED_
#pragma pack(push,1)
typedef struct _S_EL4132_Input_Prozessabbild
{
	bool WcState;
	USHORT State;
	AmsAddr AdsAddr;
} S_EL4132_Input_Prozessabbild, *PS_EL4132_Input_Prozessabbild;
#pragma pack(pop)
#endif // !defined(_TC_TYPE_74959CEA_91AC_4705_A895_00BB30773892_INCLUDED_)

#if !defined(_TC_TYPE_0612D231_FCCB_4A1E_92B1_B91B8C849151_INCLUDED_)
#define _TC_TYPE_0612D231_FCCB_4A1E_92B1_B91B8C849151_INCLUDED_
typedef struct _S_EL4132_Output_Prozessabbild
{
	SHORT Output_0;
	SHORT Output_1;
} S_EL4132_Output_Prozessabbild, *PS_EL4132_Output_Prozessabbild;
#endif // !defined(_TC_TYPE_0612D231_FCCB_4A1E_92B1_B91B8C849151_INCLUDED_)

#if !defined(_TC_TYPE_37F2006B_CA63_41BD_8992_0266C6115244_INCLUDED_)
#define _TC_TYPE_37F2006B_CA63_41BD_8992_0266C6115244_INCLUDED_
#pragma pack(push,1)
typedef struct _S_EL5151_Input_Prozessabbild
{
	USHORT ENC_Status;
	LONG ENC_CounterValue;
	LONG ENC_LatchValue;
	LONG ENC2_PeriodValue;
	ULONGLONG ENC3_Timestamp;
	bool WcState;
	bool InputToggle;
	USHORT State;
	AmsAddr AdsAddr;
} S_EL5151_Input_Prozessabbild, *PS_EL5151_Input_Prozessabbild;
#pragma pack(pop)
#endif // !defined(_TC_TYPE_37F2006B_CA63_41BD_8992_0266C6115244_INCLUDED_)

#if !defined(_TC_TYPE_D35D150F_D896_4154_9AA3_F3F4BFC37792_INCLUDED_)
#define _TC_TYPE_D35D150F_D896_4154_9AA3_F3F4BFC37792_INCLUDED_
#pragma pack(push,1)
typedef struct _S_EL5151_Output_Prozessabbild
{
	USHORT ENC_Control;
	LONG ENC_SetCounterValue;
} S_EL5151_Output_Prozessabbild, *PS_EL5151_Output_Prozessabbild;
#pragma pack(pop)
#endif // !defined(_TC_TYPE_D35D150F_D896_4154_9AA3_F3F4BFC37792_INCLUDED_)

#if !defined(_TC_TYPE_67B7AA65_A8D8_4053_BEBE_8169A6CFF813_INCLUDED_)
#define _TC_TYPE_67B7AA65_A8D8_4053_BEBE_8169A6CFF813_INCLUDED_
typedef struct _S_EL6002_Input_Prozessabbild
{
	USHORT COM0_Status;
	USHORT COM0_DataIn[22];
	USHORT COM1_Status;
	USHORT COM1_DataIn[22];
	bool WcState;
	bool InputToggle;
	USHORT State;
	AmsAddr AdsAddr;
} S_EL6002_Input_Prozessabbild, *PS_EL6002_Input_Prozessabbild;
#endif // !defined(_TC_TYPE_67B7AA65_A8D8_4053_BEBE_8169A6CFF813_INCLUDED_)

#if !defined(_TC_TYPE_E1914AC9_E4CE_4822_8A1B_AA133FF23355_INCLUDED_)
#define _TC_TYPE_E1914AC9_E4CE_4822_8A1B_AA133FF23355_INCLUDED_
typedef struct _S_EL6002_Output_Prozessabbild
{
	USHORT COM0_Ctrl;
	USHORT COM0_DataOut[22];
	USHORT COM1_Ctrl;
	USHORT COM1_DataOut[22];
} S_EL6002_Output_Prozessabbild, *PS_EL6002_Output_Prozessabbild;
#endif // !defined(_TC_TYPE_E1914AC9_E4CE_4822_8A1B_AA133FF23355_INCLUDED_)

#if !defined(_TC_TYPE_DBCB4CA8_0A62_4B86_BC0B_5A381153FB00_INCLUDED_)
#define _TC_TYPE_DBCB4CA8_0A62_4B86_BC0B_5A381153FB00_INCLUDED_
#pragma pack(push,1)
typedef struct _S_EL7031_Input_Prozessabbild
{
	USHORT ENC_Status;
	LONG ENC_CounterValue;
	LONG ENC_LatchValue;
	USHORT STM_Status;
	bool WcState;
	bool InputToggle;
	USHORT State;
	AmsAddr AdsAddr;
	unsigned char Chn_0;
	unsigned char Chn_1;
} S_EL7031_Input_Prozessabbild, *PS_EL7031_Input_Prozessabbild;
#pragma pack(pop)
#endif // !defined(_TC_TYPE_DBCB4CA8_0A62_4B86_BC0B_5A381153FB00_INCLUDED_)

#if !defined(_TC_TYPE_F56C0356_FB67_482C_9A6F_663E1C54AD18_INCLUDED_)
#define _TC_TYPE_F56C0356_FB67_482C_9A6F_663E1C54AD18_INCLUDED_
#pragma pack(push,1)
typedef struct _S_EL7031_Output_Prozessabbild
{
	USHORT ENC_Control;
	LONG ENC_SetCounterValue;
	USHORT STM_Control;
	SHORT STM_Velocity;
} S_EL7031_Output_Prozessabbild, *PS_EL7031_Output_Prozessabbild;
#pragma pack(pop)
#endif // !defined(_TC_TYPE_F56C0356_FB67_482C_9A6F_663E1C54AD18_INCLUDED_)

#if !defined(_TC_TYPE_2ACAAB64_DCD3_4E65_8727_E8B196B47E8F_INCLUDED_)
#define _TC_TYPE_2ACAAB64_DCD3_4E65_8727_E8B196B47E8F_INCLUDED_
#pragma pack(push,1)
typedef struct _S_EL7201_Input_Prozessabbild
{
	LONG FB_Position;
	USHORT DRV_Statusword;
	bool WcState;
	bool InputToggle;
	USHORT State;
	AmsAddr AdsAddr;
	unsigned char Chn0;
	LONG DcOutputShift;
	LONG DcInputShift;
} S_EL7201_Input_Prozessabbild, *PS_EL7201_Input_Prozessabbild;
#pragma pack(pop)
#endif // !defined(_TC_TYPE_2ACAAB64_DCD3_4E65_8727_E8B196B47E8F_INCLUDED_)

#if !defined(_TC_TYPE_E6341AE8_3480_4FA3_9A33_7F04AB343C46_INCLUDED_)
#define _TC_TYPE_E6341AE8_3480_4FA3_9A33_7F04AB343C46_INCLUDED_
#pragma pack(push,1)
typedef struct _S_EL7201_Output_Prozessabbild
{
	USHORT DRV_Controlword;
	LONG DRV_TargetVelocity;
} S_EL7201_Output_Prozessabbild, *PS_EL7201_Output_Prozessabbild;
#pragma pack(pop)
#endif // !defined(_TC_TYPE_E6341AE8_3480_4FA3_9A33_7F04AB343C46_INCLUDED_)

#if !defined(_TC_TYPE_695E1320_35E5_4DF5_9470_6A34A9B6A58C_INCLUDED_)
#define _TC_TYPE_695E1320_35E5_4DF5_9470_6A34A9B6A58C_INCLUDED_
typedef struct _S_EL5151_Input_Pendel
{
	USHORT CounterValue;
} S_EL5151_Input_Pendel, *PS_EL5151_Input_Pendel;
#endif // !defined(_TC_TYPE_695E1320_35E5_4DF5_9470_6A34A9B6A58C_INCLUDED_)

#if !defined(_TC_TYPE_EDF276E6_D2E9_492F_9111_C725E931C44F_INCLUDED_)
#define _TC_TYPE_EDF276E6_D2E9_492F_9111_C725E931C44F_INCLUDED_
#pragma pack(push,1)
typedef struct _S_EL5151_Output_Pendel
{
} S_EL5151_Output_Pendel, *PS_EL5151_Output_Pendel;
#pragma pack(pop)
#endif // !defined(_TC_TYPE_EDF276E6_D2E9_492F_9111_C725E931C44F_INCLUDED_)

#pragma pack(push,1)
typedef struct _KM_App_MainInputs
{
	S_EL1012_Input_Prozessabbild EL1012_DigitalInput_Klemme;
	S_EL1014_Input_Prozessabbild EL1014_DigitalInput_Klemme0;
	S_EL1014_Input_Prozessabbild EL1014_DigitalInput_Klemme1;
	S_EL2004_Input_Prozessabbild EL2004_DigitalOutput_Klemme0;
	S_EL2004_Input_Prozessabbild EL2004_DigitalOutput_Klemme1;
	S_EL2502_Input_Prozessabbild EL2502_PwmOutput_Klemme;
	S_EL3162_Input_Prozessabbild EL3162_AnalogInput_Klemme;
	S_EL3202_Input_Prozessabbild EL3202_RtdAnalogInput_Klemme;
	S_EL4132_Input_Prozessabbild EL4132_AnalogOutput_Klemme;
	S_EL5151_Input_Prozessabbild EL5151_Drehgeber_Klemme;
	S_EL5151_Input_Prozessabbild EL5151_Lineargeber_Klemme;
	S_EL7201_Input_Prozessabbild EL7201_ServoMotor_Klemme;
	S_EK1100_Input_Prozessabbild EK1100_EtherCAT_Koppler;
	S_EL5151_Input_Pendel EL5151_Pendel_drehgeber;
} KM_App_MainInputs, *PKM_App_MainInputs;
#pragma pack(pop)

#pragma pack(push,1)
typedef struct _KM_App_MainOutputs
{
	S_EL1012_Output_Prozessabbild EL1012_DigitalInput_Klemme;
	S_EL1014_Output_Prozessabbild EL1014_DigitalInput_Klemme0;
	S_EL1014_Output_Prozessabbild EL1014_DigitalInput_Klemme1;
	S_EL2004_Output_Prozessabbild EL2004_DigitalOutput_Klemme0;
	S_EL2004_Output_Prozessabbild EL2004_DigitalOutput_Klemme1;
	S_EL2502_Output_Prozessabbild EL2502_PwmOutput_Klemme;
	S_EL3162_Output_Prozessabbild EL3162_AnalogInput_Klemme;
	S_EL3202_Output_Prozessabbild EL3202_RtdAnalogInput_Klemme;
	S_EL4132_Output_Prozessabbild EL4132_AnalogOutput_Klemme;
	S_EL5151_Output_Prozessabbild EL5151_Drehgeber_Klemme;
	S_EL5151_Output_Prozessabbild EL5151_Lineargeber_Klemme;
	S_EL7201_Output_Prozessabbild EL7201_ServoMotor_Klemme;
	S_EK1100_Output_Prozessabbild EK1100_EtherCAT_Koppler;
	S_EL5151_Output_Pendel EL5151_Pendel_drehgeber;
} KM_App_MainOutputs, *PKM_App_MainOutputs;
#pragma pack(pop)

///</AutoGeneratedContent>



///<AutoGeneratedContent id="DataAreaIDs">
#define ADI_KM_App_MainInputs 0
#define ADI_KM_App_MainOutputs 1
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="EventClasses">
///</AutoGeneratedContent>
